name: Fetch latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '33 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Fetch latest
      run: |
        curl https://edge.microsoft.com/neededge/v1 > v1.xml
    - name: Commit and push if s changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
